name: Whoami
description: Validate your token against SI
author: jkeiser@systeminit.com

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  apiToken:
    description: |
      The API token. You can create one by going to
      https://auth.systeminit.com/workspaces/, clicking on the Settings (gear)
      icon on your workspace, and selecting "API Tokens." Then enter a name and
      expiration, and click "Generate API Token."

      You should use GitHub's secrets mechanism to store and pass this.
    required: true
  apiUrl:
    description:
      The URL to the SI instance's API server. This is optional, and generally
      points to SI's hosted API service by default.

# Define your outputs here.
outputs:
  workspaceId:
    description: The ID of the workspace for the token.
  userId:
    description: The user ID.
  userEmail:
    description: The email address of the workspace owner.

runs:
  using: node20
  main: ../dist/index.js
